---
name: login

spring_profiles: ldap

ldap.url: ldap://localhost:22389/dc=cloudfoundry,dc=com
ldap.usersDn: "uid={0},ou=users"

uaa:
  url: https://uaa.cf.com
  token:
    url: https://uaa.cf.com/oauth/token
  login:
    url: https://uaa.cf.com/authenticate
  clientinfo:
    url: https://uaa.cf.com/clientinfo

#require_https: true
dump_requests: true

